FROM jenkins/jenkins:lts-jdk21

USER root

RUN apt-get update && apt-get install -y docker.io openssh-client && rm -rf /var/lib/apt/lists/*

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER jenkins

RUN jenkins-plugin-cli --plugins workflow-aggregator git

ENTRYPOINT ["/entrypoint.sh"]
